# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  if Vagrant.has_plugin? "vagrant-vbguest"
    config.vbguest.no_install = true
    config.vbguest.auto_update = false
    config.vbguest.no_remote = true
  end
  config.vm.define :servidorFront do |servidorFront|
    servidorFront.vm.box = "bento/ubuntu-22.04"
    servidorFront.vm.network :private_network, ip: "192.168.100.3"
    servidorFront.vm.hostname = "servidorFront"
    servidorFront.vm.box_download_insecure=true
  end
  config.vm.define :servidorBack do |servidorBack|
    servidorBack.vm.box = "bento/ubuntu-22.04"
    servidorBack.vm.network :private_network, ip: "192.168.100.2"
    servidorBack.vm.hostname = "servidorBack"
    servidorBack.vm.box_download_insecure=true

    servidorBack.vm.synced_folder "../Backend", "/home/vagrant/BackendUbuntu"
  end
end